# Generated by Django 2.2.3 on 2020-01-21 07:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonal',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.jsonb.JSONField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('emergency', django.contrib.postgres.fields.jsonb.JSONField()),
                ('education', django.contrib.postgres.fields.jsonb.JSONField()),
                ('links', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
                'db_table': 'employee_personal',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.jsonb.JSONField()),
                ('number_of_days', models.SmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'timesheet',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfessional',
            fields=[
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.EmployeePersonal')),
                ('emp_pass', models.CharField(blank=True, max_length=256, null=True)),
                ('name', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', django.contrib.postgres.fields.jsonb.JSONField()),
                ('child', django.contrib.postgres.fields.jsonb.JSONField()),
                ('activity', django.contrib.postgres.fields.jsonb.JSONField()),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'employee_professional',
            },
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.EmployeeProfessional')),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_ac_no', models.BigIntegerField(blank=True, null=True)),
                ('pf_uan', models.BigIntegerField(blank=True, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('esi_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gross_pay', models.SmallIntegerField(blank=True, null=True)),
                ('net_pay', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'pay_info',
            },
        ),
    ]
